config/routes.rb
Rails.application.routes.draw do

  root 'home#home'

  get 'home/home'
  get 'home/about'
  get 'home/services'
  get 'home/contact'
  get 'home/portfolio'

  get '/admin' , to: 'panel_page_indices#index'
  

  resources :page_indices
  resources :panel_page_indices

end

app/models/page_contact.rb
class PageContact < ActiveRecord::Base
end

app/models/page_index.rb
class PageIndex < ActiveRecord::Base
  
end

app/models/panel_page_index.rb
class PanelPageIndex < ActiveRecord::Base
  validates :title_panel, :body_panel ,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @panels = PanelPageIndex.paginate(:page => params[:page], :per_page => 6).order(id: :desc)
  end

  def about
  end

  def services
  end

  def contact
    @contact = PageContact.first
  end

  def portfolio
  end
end

app/controllers/page_indices_controller.rb
class PageIndicesController < ApplicationController
  layout 'admin'
  before_action :set_page_index, only: [:show, :edit, :update, :destroy]

  # GET /page_indices
  # GET /page_indices.json
  def index
    @page_indices = PageIndex.all
  end

  # GET /page_indices/1
  # GET /page_indices/1.json
  def show
  end

  # GET /page_indices/new
  def new
    @page_index = PageIndex.new
  end

  # GET /page_indices/1/edit
  def edit
  end

  # POST /page_indices
  # POST /page_indices.json
  def create
    @page_index = PageIndex.new(page_index_params)

    respond_to do |format|
      if @page_index.save
        format.html { redirect_to @page_index, notice: 'Page index was successfully created.' }
        format.json { render :show, status: :created, location: @page_index }
      else
        format.html { render :new }
        format.json { render json: @page_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_indices/1
  # PATCH/PUT /page_indices/1.json
  def update
    respond_to do |format|
      if @page_index.update(page_index_params)
        format.html { redirect_to @page_index, notice: 'Page index was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_index }
      else
        format.html { render :edit }
        format.json { render json: @page_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_indices/1
  # DELETE /page_indices/1.json
  def destroy
    @page_index.destroy
    respond_to do |format|
      format.html { redirect_to page_indices_url, notice: 'Page index was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_index
      @page_index = PageIndex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_index_params
      params[:page_index]
    end
end

app/controllers/panel_page_indices_controller.rb
class PanelPageIndicesController < ApplicationController
  layout 'admin'
  before_action :set_panel_page_index, only: [:show, :edit, :update, :destroy]

  # GET /panel_page_indices
  # GET /panel_page_indices.json
  def index
    @panel_page_indices = PanelPageIndex.all
  end

  # GET /panel_page_indices/1
  # GET /panel_page_indices/1.json
  def show
  end

  # GET /panel_page_indices/new
  def new
    @panel_page_index = PanelPageIndex.new
  end

  # GET /panel_page_indices/1/edit
  def edit
  end

  # POST /panel_page_indices
  # POST /panel_page_indices.json
  def create
    @panel_page_index = PanelPageIndex.new(panel_page_index_params)

    respond_to do |format|
      if @panel_page_index.save
        format.html { redirect_to @panel_page_index, notice: 'Painel criado com sucesso' }
        format.json { render :show, status: :created, location: @panel_page_index }
      else
        format.html { render :new }
        format.json { render json: @panel_page_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panel_page_indices/1
  # PATCH/PUT /panel_page_indices/1.json
  def update
    respond_to do |format|
      if @panel_page_index.update(panel_page_index_params)
        format.html { redirect_to @panel_page_index, notice: 'Painel atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @panel_page_index }
      else
        format.html { render :edit }
        format.json { render json: @panel_page_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panel_page_indices/1
  # DELETE /panel_page_indices/1.json
  def destroy
    @panel_page_index.destroy
    respond_to do |format|
      format.html { redirect_to panel_page_indices_url, notice: 'Painel deletado com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel_page_index
      @panel_page_index = PanelPageIndex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_page_index_params
      params.require(:panel_page_index).permit(:title_panel, :body_panel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_indices_helper.rb
module PageIndicesHelper
end

app/helpers/panel_page_indices_helper.rb
module PanelPageIndicesHelper
end

app/views/home/about.html.erb
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">SOBRE
                    <small></small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="<%= root_path %>">Início</a>
                    </li>
                    <li class="active">Sobre</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Intro Content -->
        <div class="row">
            <div class="col-md-6">
                <img class="img-responsive" src="http://www.maceio.al.gov.br/wp-content/uploads/admin/imagem/2013/12/1312-Fachadas-das-Secretarias-Municipais-PF-0022.jpg" alt="">
            </div>
            <div class="col-md-6">
                <h2>SEMED</h2>
                <p>A Secretaria Municipal de Educação (Semed) é um órgão da Prefeitura Municipal de Maceió que tem por finalidade formular e garantir a política municipal de educação.</p>
                <p><strong>À Semed, cabe:</strong></p>
                - Formular, executar, controlar e garantir a Política Municipal de Educação; </br>
                - Prover e garantir a universalização do acesso à educação infantil e ao ensino fundamental; </br>
                - Oferecer ensino obrigatório e gratuito para crianças, jovens, adultos e pessoas portadoras de necessidades especiais; </br>
                - Efetuar o gerenciamento escolar e a pesquisa educacional; </br>
                - Zelar pela qualidade do ensino público em nível municipal.
            
        </div>
        <small>fonte: http://www.maceio.al.gov.br/semed/institucional/</small> 
        <!-- /.row -->

        <!-- Team Members
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <div class="caption">
                        <h3>John Smith<br>
                            <small>Job Title</small>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <div class="caption">
                        <h3>John Smith<br>
                            <small>Job Title</small>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <div class="caption">
                        <h3>John Smith<br>
                            <small>Job Title</small>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <div class="caption">
                        <h3>John Smith<br>
                            <small>Job Title</small>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <div class="caption">
                        <h3>John Smith<br>
                            <small>Job Title</small>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                    <div class="caption">
                        <h3>John Smith<br>
                            <small>Job Title</small>
                        </h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste saepe et quisquam nesciunt maxime.</p>
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> -->
        <!-- /.row -->

        <!-- Our Customers 
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Customers</h2>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <img class="img-responsive customer-img" src="http://placehold.it/500x300" alt="">
            </div>
        </div>-->
        <!-- /.row -->

        <hr>
</div>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright © departamento de TI SEMED</p>
                </div>
            </div>
        </footer>
    
</div>

app/views/home/contact.html.erb
<!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">CONTATO
                    <small></small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="<%= root_path %>">Início</a>
                    </li>
                    <li class="active">Contato</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div class="col-md-8">
                
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7866.737605662207!2d-35.74196073865356!3d-9.649494614775655!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7014f62fb3b4f29%3A0x2d81ed3a2215d00d!2sSecretaria+Municipal+de+Educa%C3%A7%C3%A3o!5e0!3m2!1spt-BR!2sbr!4v1443060133924" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Nossos dados</h3>
                <p>
                    <%= @contact.patio %><br><%= @contact.district %><br>
                </p>
                <p><i class="fa fa-phone"></i>
                    <abbr title="Phone"></abbr>: <%= @contact.phone %></p>
                <p><i class="fa fa-envelope-o"></i>
                    <abbr title="Email"></abbr>: <a href=""><%= @contact.email %></a>
                </p>
                <!--<p><i class="fa fa-clock-o"></i>
                    <abbr title="Hours"></abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>-->
            </div>
        </div>
        <!-- /.row -->

        <!-- Contact Form -->
        <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
       <!-- <div class="row">
            <div class="col-md-8">
                <h3>Send us a Message</h3>
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Full Name:</label>
                            <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Phone Number:</label>
                            <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Email Address:</label>
                            <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Message:</label>
                            <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                        </div>
                    </div>
                    <div id="success"></div>
                    <!-- For success/fail messages 
                    <button type="submit" class="btn btn-primary">Send Message</button>
                </form>-->
            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-sm-12 col-sm-offset-1">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>SemedTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 0px;">

 <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        SEMED
                    </a>
                </li>
                <li>
                  <%= link_to 'imagens' , panel_page_indices_path %>
                </li>
                <li>
                  <%= link_to 'index' , panel_page_indices_path %>
                </li>
                <li>
                    <a href="#">Sobre</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Serviços</a>
                </li>
                <li>
                    <a href="#">Contato</a>
                </li>
                <li>
                    <a href="#">Projetos</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                      <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>SemedTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color: #FFF;border: none;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" src="" href="<%= root_path %>" >SEMED</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="red-li">
                        <%=  link_to 'Início' , root_path %>
                    </li>
                    <li class="light-green-li">
                        <%=  link_to 'Sobre' , home_about_path %>
                    </li>
                    <li class="green-li">
                        <%=  link_to 'Serviços' , home_services_path %>
                    </li>
                    <li class="orange-li">
                        <%=  link_to 'Contato' , home_contact_path %>
                    </li>
                    <!-- <li class="blue-li">-->
                        <%#=  link_to 'Projetos' , home_portfolio_path %>
                   <!-- </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<%= yield %>

  <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    });
  </script>
</body>
</html>

app/views/page_indices/_form.html.erb
<%= form_for(@page_index) do |f| %>
  <% if @page_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page_index.errors.count, "error") %> prohibited this page_index from being saved:</h2>

      <ul>
      <% @page_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/page_indices/edit.html.erb
<h1>Editing Page Index</h1>

<%= render 'form' %>

<%= link_to 'Show', @page_index %> |
<%= link_to 'Back', page_indices_path %>

app/views/page_indices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Page Indices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_indices.each do |page_index| %>
      <tr>
        <td><%= link_to 'Show', page_index %></td>
        <td><%= link_to 'Edit', edit_page_index_path(page_index) %></td>
        <td><%= link_to 'Destroy', page_index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page index', new_page_index_path %>

app/views/page_indices/new.html.erb
<h1>New Page Index</h1>

<%= render 'form' %>

<%= link_to 'Back', page_indices_path %>

app/views/page_indices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_index_path(@page_index) %> |
<%= link_to 'Back', page_indices_path %>

app/views/panel_page_indices/_form.html.erb
<%= form_for(@panel_page_index) do |f| %>
  <% if @panel_page_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panel_page_index.errors.count, "error") %> prohibited this panel_page_index from being saved:</h2>

      <ul>
      <% @panel_page_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-sm-12">  
    <div>
      <%= f.label 'título do painel' %><br>
      <%= f.text_field :title_panel, class: 'form form-control' %>
    </div>
    <div>
      <%= f.label 'título do painel' %><br>
      <%= f.text_area :body_panel, class: 'form form-control' %>
    </div><br>
    <div class="actions">
    <%= f.submit "salvar", class: 'btn btn-primary' %> | <%= link_to 'voltar', panel_page_indices_path %>
  </div>
  </div>
    
  
<% end %>

app/views/panel_page_indices/edit.html.erb
<div class="container">
	<h1>Editar Painel</h1>

	<%= render 'form' %>
</div>

app/views/panel_page_indices/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-12">
<h1>Paineis cadastrados na página index</h1>
<%= link_to 'novo painel', new_panel_page_index_path , class: 'btn btn-primary col-sm-3 col-sm-offset-8' %>
  <br><br>
  <table class="table table-striped well">
    <thead>
      <tr>
        <th></th>
        <th>Título</th>
        <th>Corpo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @panel_page_indices.each do |panel_page_index| %>
        <tr>
          <td></td>
          <td><%= panel_page_index.title_panel %></td>
          <td><%= panel_page_index.body_panel %></td>
          <td><%#= link_to 'exibir', panel_page_index, class: 'btn btn-info btn-xs' %></td>
          <td><%= link_to 'editar', edit_panel_page_index_path(panel_page_index), class: 'btn btn-info btn-xs' %>
          <%= link_to 'excluir', panel_page_index, method: :delete, data: { confirm: 'quer mesmo deletar?' }, class: 'btn btn-danger btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/panel_page_indices/new.html.erb
<div class="container">
<h1>Cadastrar Painel</h1>

<%= render 'form' %>


</div>

app/views/panel_page_indices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_panel_page_index_path(@panel_page_index) %> |
<%= link_to 'Back', panel_page_indices_path %>